### ISSUE TITLE
Error on Function??

### ISSUE THREAD

**Issue by jaylac2000** [iAlen17/Alen-FIB#1]
[     script:Alen-FIB] Error loading script server.lua in resource Alen-FIB: citizen:/scripting/lua/scheduler.lua:1155: No such export GetCoreObject in resource qb-core
[     script:Alen-FIB] stack traceback:
[     script:Alen-FIB] 	[C]: in function 'error'
[     script:Alen-FIB] 	citizen:/scripting/lua/scheduler.lua:1155: in metamethod '__index'
[     script:Alen-FIB] 	@Alen-FIB/server.lua:2: in main chunk
[    c-scripting-core] Failed to load script server.lua.

**Comment by iAlen17** [comment]
This is not an error in the script it is because the version of your Framework is different in terms of triggering GetObject. Hence this is being closed.
